name: syth_hotel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  change_app_package_name: ^1.4.0
  cloud_firestore: ^5.5.1
  d_info: ^0.2.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  intl: ^0.20.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/
